//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaGubisch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Rack {
            get {
                return ((short)(this["Rack"]));
            }
            set {
                this["Rack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public short Slot {
            get {
                return ((short)(this["Slot"]));
            }
            set {
                this["Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CpuType.S7300")]
        public string CPUType {
            get {
                return ((string)(this["CPUType"]));
            }
            set {
                this["CPUType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RefreshFreq {
            get {
                return ((int)(this["RefreshFreq"]));
            }
            set {
                this["RefreshFreq"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.90.94")]
        public string IP {
            get {
                return ((string)(this["IP"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\chipbreaker.png")]
        public string PATHchipbreaker {
            get {
                return ((string)(this["PATHchipbreaker"]));
            }
            set {
                this["PATHchipbreaker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\DP_station.png")]
        public string PATHDP_Station {
            get {
                return ((string)(this["PATHDP_Station"]));
            }
            set {
                this["PATHDP_Station"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\feedbeam_rollers.png")]
        public string PATHfeedbeamRollers {
            get {
                return ((string)(this["PATHfeedbeamRollers"]));
            }
            set {
                this["PATHfeedbeamRollers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\groove_spindle.png")]
        public string PATHgroovespindle {
            get {
                return ((string)(this["PATHgroovespindle"]));
            }
            set {
                this["PATHgroovespindle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\guidens.png")]
        public string PATHguidens {
            get {
                return ((string)(this["PATHguidens"]));
            }
            set {
                this["PATHguidens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\saw_unit.png")]
        public string PATHsawunit {
            get {
                return ((string)(this["PATHsawunit"]));
            }
            set {
                this["PATHsawunit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\servicemodule.png")]
        public string PATHservicemodulepic {
            get {
                return ((string)(this["PATHservicemodulepic"]));
            }
            set {
                this["PATHservicemodulepic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\spindle_horizontal.png")]
        public string PATHspindlehorizontal {
            get {
                return ((string)(this["PATHspindlehorizontal"]));
            }
            set {
                this["PATHspindlehorizontal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.90.203\\common\\Programy\\Aplikacja Gubisch\\tenon_visior.png")]
        public string PATHtenonvisior {
            get {
                return ((string)(this["PATHtenonvisior"]));
            }
            set {
                this["PATHtenonvisior"] = value;
            }
        }
    }
}
